my_string = input("Введите свою фамилию,имя: ")
print(
    f"{my_string},{len(my_string)}, {my_string.upper()}, {my_string.lower()}, {my_string.replace(" ", "")}, {my_string[0]}, {my_string[-1]}.")
print(len(my_string))
print(my_string)
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ", ""))
print(my_string[0])
print(my_string[-1])
